name: ephone_field
description: A versatile Flutter TextFormField widget for handling email and phone number input with ease.
version: 0.0.1
homepage: ephone_field 

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/flags/
